import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Home, Lightbulb, Leaf, Wallet, ArrowRight, ZapOff, ChevronDown } from 'lucide-react';
import { ContactModal } from './ContactModal';

export const Consumers = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqs = [
    {
      q: "Do I need to install solar panels or buy a battery?",
      a: "No! That's the beauty of Tiny Hub. As a consumer, you simply purchase the clean energy generated by the 'Prosumers' in your community. No hardware installation is required."
    },
    {
      q: "Is it legal to switch from my current utility provider?",
      a: "Yes. In deregulated energy markets, you have the legal right to choose your energy provider. Tiny Hub handles the seamless transition without any interruption to your power."
    },
    {
      q: "What happens if local prosumers don't produce enough energy?",
      a: "The network is always backed by the broader grid. If local micro-grid production dips due to weather or high demand, your home automatically pulls from the standard grid to ensure 100% uptime."
    },
    {
      q: "Are there any hidden fees or long-term contracts?",
      a: "No. Our pricing is completely transparent. We charge a flat, minimal network fee per kWh traded, and you can cancel your participation at any time with no penalty."
    }
  ];

  return (
    <div className="relative w-full overflow-hidden pb-20">
       {/* Background Glows */}
      <div className="absolute inset-0 z-0 pointer-events-none">
        <motion.div
           animate={{ scale: [1, 1.2, 1], opacity: [0.1, 0.2, 0.1] }}
           transition={{ duration: 15, repeat: Infinity, ease: "easeInOut" }}
           className="absolute top-[10%] right-[0%] sm:right-[-10%] w-[300px] h-[300px] sm:w-[500px] sm:h-[500px] bg-tinysky/20 rounded-full blur-[100px] sm:blur-[120px]"
        />
      </div>

      <div className="relative z-10 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-24 pt-12">
        {/* Hero Section */}
        <section className="text-center max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-display font-bold text-transparent bg-clip-text bg-gradient-to-r from-tinysky to-tinyorange mb-8 tracking-tight leading-tight">
              A Smarter Way to <br className="hidden sm:block" /> 
              Power Your Life
            </h1>
            <div className="bg-tinysky/20 border border-tinysky/30 rounded-3xl p-8">
              <p className="text-lg md:text-xl text-white font-bold leading-relaxed">
                Stop overpaying centralized monopolies for dirty energy imported from miles away. Tiny Hub connects you directly to the clean energy generated by your own community.
              </p>
            </div>
          </motion.div>
        </section>

        {/* Features */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8 lg:gap-12">
            {[
              {
                icon: <Wallet className="w-8 h-8" />,
                title: "Cheaper, Transparent Rates",
                desc: "By removing the massive overhead of legacy infrastructure and middlemen, energy traded on the decentralized network is structurally cheaper."
              },
              {
                icon: <Leaf className="w-8 h-8" />,
                title: "Locally Sourced Clean Energy",
                desc: "Know exactly where your power comes from. Subsidize your neighbors' solar panels instead of foreign fossil fuels."
              },
              {
                icon: <ZapOff className="w-8 h-8" />,
                title: "Resilience in Blackouts",
                desc: "As local microgrids grow, you become insulated from cascading grid failures affecting the broader state network."
              },
              {
                icon: <Home className="w-8 h-8" />,
                title: "Seamless Transition",
                desc: "Switching connects your existing utility connection logically to the DePIN. No new wires, no drilling, no hassle."
              }
            ].map((feature, i) => (
                <motion.div
                   key={i}
                   initial={{ opacity: 0, y: 20 }}
                   whileInView={{ opacity: 1, y: 0 }}
                   viewport={{ once: true }}
                   transition={{ delay: i * 0.1 }}
                   className="bg-[#111111] p-8 rounded-[2rem] shadow-sm border border-white/10 flex flex-col sm:flex-row gap-6 hover:shadow-md transition-shadow group"
                >
                    <div className="flex-shrink-0">
                       <div className="p-4 bg-[#0a0a0a] text-tinysky rounded-2xl border border-tinysky/20">
                          {feature.icon}
                       </div>
                    </div>
                    <div>
                       <h3 className="text-2xl font-bold text-tinysky mb-3">{feature.title}</h3>
                       <p className="text-neutral-400 font-light leading-relaxed">{feature.desc}</p>
                    </div>
                </motion.div>
            ))}
        </section>

        {/* How It Works (4 Steps) */}
        <section className="pt-12">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-center text-white mb-12">How It Works</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              { title: "Sign Up", desc: "Create your free Tiny Hub profile in under 2 minutes." },
              { title: "Switch Provider", desc: "Authorize the logically-seamless switch from your legacy utility." },
              { title: "Smart Sourcing", desc: "Our algorithm automatically buys the cheapest local renewable energy for you." },
              { title: "Save Money", desc: "Enjoy immediate reductions on your monthly energy bill." }
            ].map((step, i) => (
              <motion.div 
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="relative bg-[#111111] p-8 rounded-3xl border border-white/5 text-center flex flex-col items-center"
              >
                <div className="w-12 h-12 bg-white/5 rounded-full flex items-center justify-center text-tinysky font-bold text-xl mb-6">
                  {i + 1}
                </div>
                <h4 className="text-white font-bold text-lg mb-3">{step.title}</h4>
                <p className="text-neutral-500 text-sm">{step.desc}</p>
                {i !== 3 && (
                  <div className="hidden lg:block absolute top-1/2 -right-4 w-8 h-[1px] bg-white/10" />
                )}
              </motion.div>
            ))}
          </div>
        </section>

        {/* Coming Soon: AI Savings Agent */}
        <section className="bg-gradient-to-br from-[#151515] to-[#0a0a0a] rounded-[3rem] p-8 md:p-12 border border-white/10 mt-12 relative overflow-hidden flex flex-col items-center text-center">
             <div className="absolute top-0 right-0 w-64 h-64 bg-tinysky/10 rounded-full blur-[100px]" />
             <div className="absolute bottom-0 left-0 w-64 h-64 bg-tinyorange/10 rounded-full blur-[100px]" />
             
             <div className="relative z-10 w-full max-w-3xl flex flex-col items-center">
                <div className="w-16 h-16 bg-white/5 border border-white/10 rounded-full flex items-center justify-center text-tinysky mb-6">
                  <Wallet className="w-8 h-8" />
                </div>
                <h3 className="text-3xl md:text-4xl font-display font-bold text-white mb-4">
                  AI Savings Analyst 
                  <span className="ml-4 inline-block text-xs align-middle uppercase tracking-widest font-semibold text-tinyorange bg-tinyorange/10 border border-tinyorange/20 px-3 py-1.5 rounded-full">
                    Coming Soon
                  </span>
                </h3>
                <p className="text-neutral-400 text-lg leading-relaxed mb-10">
                  Soon, you will be able to upload your recent electric bills directly to Tiny Hub. Our AI agent will analyze your current usage patterns and rates to generate a personalized, highly accurate savings report.
                </p>
                
                <div className="flex flex-col sm:flex-row gap-4 items-center justify-center opacity-50 pointer-events-none w-full max-w-xl">
                    <div className="w-full bg-[#111111] border-2 border-white/10 border-dashed rounded-2xl p-6 flex flex-col items-center justify-center gap-2 text-neutral-500">
                        <span className="text-sm font-medium">Drag & drop your bill here</span>
                        <span className="text-xs">Supports PDF, JPG, PNG</span>
                    </div>
                </div>
             </div>
        </section>

        {/* FAQ */}
        <section className="max-w-3xl mx-auto pt-16">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-center text-white mb-10">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <div key={i} className="bg-[#111111] border border-white/10 rounded-2xl overflow-hidden transition-all duration-300">
                <button 
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex justify-between items-center p-6 text-left active:bg-white/5 transition-colors"
                >
                  <span className="font-semibold text-white pr-4">{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 text-neutral-500 transition-transform duration-300 ${openFaq === i ? 'rotate-180' : ''}`} />
                </button>
                <AnimatePresence>
                  {openFaq === i && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden"
                    >
                       <div className="p-6 pt-0 text-neutral-400 text-sm leading-relaxed border-t border-white/5 mt-2">
                         {faq.a}
                       </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="bg-gradient-to-tr from-tinysky/10 via-[#0a0a0a] to-transparent rounded-[3rem] p-10 md:p-16 border border-tinysky/20 flex flex-col items-center text-center shadow-lg shadow-tinysky/5">
             <Lightbulb className="w-12 h-12 text-tinysky mb-6" />
             <h3 className="text-3xl md:text-4xl lg:text-5xl font-display font-bold text-white mb-6">Ready to unplug from the monopoly?</h3>
             <p className="text-lg md:text-xl text-neutral-400 font-light max-w-2xl mx-auto mb-10 leading-relaxed">
               Join the waitlist to become a Tiny Hub consumer. Our goal is to aggressively expand our coverage areas and onboard new neighborhoods on a monthly basis.
             </p>
             <div className="flex flex-col sm:flex-row gap-4 w-full max-w-md mx-auto">
                <button 
                  onClick={() => setIsModalOpen(true)}
                  className="px-8 py-4 w-full bg-tinysky text-white rounded-full font-medium shadow-lg shadow-tinysky/20 whitespace-nowrap flex items-center justify-center gap-2"
                >
                  Verify Coverage
                  <ArrowRight className="w-5 h-5" />
                </button>
             </div>
        </section>

      </div>
      
      <ContactModal 
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title="Verify Coverage"
        description="Enter your email and zip code so we can let you know when the decentralized network is available in your neighborhood."
        type="email"
      />
    </div>
  );
};
